language: php

php: 5.6

services: mongodb

env:
  global:
    - SYMFONY__PRIVATE_KEY__PASS_PHRASE=testing
    - SYMFONY__DATABASE_SERVER="mongodb://localhost:27017"
    - SYMFONY__DATABASE_NAME="cinderella_test"

before_install:
  - echo $SYMFONY__PRIVATE_KEY__PASS_PHRASE
  - echo $SYMFONY__DATABASE_SERVER
  - echo $SYMFONY__DATABASE_NAME
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - rm -rf app/config/parameters.yml
  - rm -rf var
  - mkdir -p var/jwt
  - openssl genrsa -passout pass:testing -out var/jwt/jwt.pem -aes256 4096
  - openssl rsa -pubout -in var/jwt/jwt.pem -passin pass:testing -out var/jwt/jwt_public.pem

install: composer install -n --prefer-source

script:
  - bin/phpunit -v --coverage-clover=coverage.clover
  - echo "error_reporting = -1 & ~E_USER_DEPRECATED" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - bin/behat

after_script:
  - sh -c 'wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover'
