score_ya_cinderella_security_login:
    pattern: /login
    schemes: [https]
    methods: [POST]

score_ya_cinderella_security_register:
    pattern: /register
    defaults:
        _controller: score_ya.cinderella.security.controller.register
        _converters:
            user:
                converter: score_ya.cinderella.request_body
                name: user
                class: ScoreYa\Cinderella\User\Model\User
                options:
                  validator:
                    groups: [registration]
    schemes: [https]
    methods: [POST]
