score_ya_cinderella_core:
  canonicalizable:
    -
      class: ScoreYa\Cinderella\User\Model\User
      event: cinderella.user.created
      property_name: email
      canonicalized_property_name: emailCanonical
    -
      class: ScoreYa\Cinderella\Template\Model\Template
      event: cinderella.template.created
      property_name: name
      canonicalized_property_name: nameCanonical

score_ya_cinderella_sdk:
  api_key: %cinderella_api_key%
  verify_ssl: %verify_ssl%
  clients:
    template:
      base_url: %cinderella_api_url%
