score_ya_cinderella_core:
  canonicalizable:
    -
      class: ScoreYa\Cinderella\User\Model\User
      event: cinderella.user.created
      property_name: email
      canonicalized_property_name: emailCanonical
    -
      class: ScoreYa\Cinderella\Multitenancy\Model\Tenant
      event: cinderella.tenant.created
      property_name: name
      canonicalized_property_name: nameCanonical
    -
      class: ScoreYa\Cinderella\Template\Model\Template
      event: cinderella.template.created
      property_name: name
      canonicalized_property_name: nameCanonical

score_ya_cinderella_sdk:
  api_key: cBRRU2W4gE5KPXnKAhDOqRoHajo7w1vFYvzFyZ3QKOE
  verify_ssl: false
  clients:
    template:
      base_url: https://nginx.nginx.dev.cinderella
