imports:
    - { resource: parameters.yml }
    - { resource: cinderella.yml }
    - { resource: security.yml }

parameters:
    app.root_dir: %kernel.root_dir%/..

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:  "%mailer_port%"
    spool:     { type: memory }

lexik_jwt_authentication:
    private_key_path: %jwt_private_path%   # ssh private key path
    public_key_path:  %jwt_public_path%   # ssh public key path
    pass_phrase:      %private_key.pass_phrase%               # ssh key pass phrase
    token_ttl:        86400                                   # token ttl - defaults to 86400

fos_rest:
    param_fetcher_listener: force
    view:
        view_response_listener: 'force'
        formats:
            html: true
            json: true
        templating_formats:
            html: true
    format_listener:
        rules:
            - { path: ^/api/template/[\w-]+, priorities: [ html, txt ], fallback_format: ~, exception_fallback_format: html, methods: [GET], prefer_extension: true }
            - { path: ^/api, priorities: [ json ], fallback_format: json }
            - { path: ^/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
    exception:
        exception_controller: 'ScoreYa\Cinderella\Bundle\CoreBundle\Controller\ExceptionController::showAction'
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true
    body_converter:
      enabled: true
      validate: true
      validation_errors_argument: violations
doctrine_mongodb:
    connections:
        default:
            server: %database_server%
    default_database: "%database_name%"
    document_managers:
        default:
            #metadata_cache_driver:
            #  class: Doctrine\Common\Cache\MemcachedCache
            #  type: memcached
            #  instance_class: Memcached
            #  host: localhost
            #  port: 11211
            mappings:
                user:
                    type: xml
                    dir: %app.root_dir%/src/User/Doctrine
                    prefix: ScoreYa\Cinderella\User\Model
                template:
                    type: xml
                    dir: %app.root_dir%/src/Template/Doctrine
                    prefix: ScoreYa\Cinderella\Template\Model
jms_serializer:
    metadata:
        directories:
            User:
                namespace_prefix: "ScoreYa\\Cinderella\\User\\Model"
                path: "%app.root_dir%/src/User/Serializer"
            Template:
                namespace_prefix: "ScoreYa\\Cinderella\\Template\\Model"
                path: "%app.root_dir%/src/Template/Serializer"

doctrine_cache:
    providers:
        template_variables_cache:
            file_system:
                extension: .template_variables.data
                directory: %kernel.cache_dir%/template_variables
