ScoreYaCinderellaTemplateBundle:
  resource: "@ScoreYaCinderellaTemplateBundle/Resources/config/routing/routing.yml"
  prefix:   /api

ScoreYaCinderellaSecurityBundle:
  resource: "@ScoreYaCinderellaSecurityBundle/Resources/config/routing/routing.yml"
  prefix:   /api

ScoreYaCinderellaUserBundle:
  resource: "@ScoreYaCinderellaUserBundle/Resources/config/routing/routing.yml"
  prefix:   /api