security:

    encoders:
        ScoreYa\Cinderella\User\Model\User:
          algorithm:            bcrypt

    providers:
        users:
            canonicalized_document: {class: ScoreYa\Cinderella\User\Model\User, property: emailCanonical}
        api_users:
            mongodb: {class: ScoreYa\Cinderella\User\Model\User, property: apiUser.apiKey}
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        register:
            pattern: ^/api/register
            stateless: true
            security: false
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            gfreeau_get_jwt:
                username_parameter: email
        api_template:
            pattern:   ^/api/template/[\w-\.]+
            stateless: true
            anonymous: false
            methods: [GET]
            simple_preauth:
                provider: api_users
                authenticator: score_ya.cinderella.security.authentication.api_key
        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt: ~
            anonymous: false

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY, requires_channel: https }
